Feature/login
f-lab-edu/inter-office pull request #2
Opened 2022-02-21 11:10 UTC by iamzin

2022-02-21 11:23 UTC, f-lab-bright commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok'
data-jpa, h2, mysql-connector-java 의존성은 전부 제거해주세요.
지금은 데이터베이스 연동 없이 구현해보셔야 합니다.
그리고 jpa는 당장 사용하지 않고, mybatis로 디비 구성을 할 예정입니다 :)

2022-02-21 11:28 UTC, f-lab-bright reviewed
Layered Architecture의 가이드대로 package 구성을 한 번 다시 정리해보면 좋을 것 같네요 :)

2022-02-21 11:28 UTC, f-lab-bright commented on src/main/java/com/interoffice/dao/AccountDao.java
> +public class AccountDao {
DAO와 Repository의 차이를 아시나요..?
어떤상황에서 Dao와 Repository를 사용하는게 더 좋을까요..?
DAO와 Repository의 개념적인 부분을 두 분 다 찾아보시면 좋을 것 같습니다.
(저는 프로젝트에서는 Repository를 사용하는 방식으로 하는걸 권장드립니다 :))
@iamzin @jws1837

2022-02-21 11:28 UTC, f-lab-bright commented on build.gradle
> +    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2'
mybatis도 우선은 제거해주세요.
디비 구성은 어느정도 진행 되고, db책을 보면서 부터 구성하고, 그 전까지는 InMemoryRepository를 구현하는 방식으로 진행할 예정입니다 :)

2022-02-21 11:28 UTC, f-lab-bright commented on src/main/java/com/interoffice/dto/Account.java
> +  private String password;
유저의 Account Entity로서 이 두 정보로 충분할까요..??
Entity는 어떤 특징을 가지고 있는 개체일까요..?

2022-02-21 12:58 UTC, f-lab-bright requested changes
이거 좀 바꿔서 반영해야 할 듯

2022-02-21 14:03 UTC, f-lab-bright commented on src/main/java/com/interoffice/service/LoginService.java
> +  String login(HttpSession session, String id, String password);
요런 주석이 꼭 필요할지도 한 번 고민해보시면 좋겠네요 :)

2022-02-23 01:35 UTC, f-lab-bright commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +      session.setAttribute("username", account.getUsername());
세션에 username만 들어가있으면 충분할까요?

2022-02-23 01:35 UTC, f-lab-bright commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +    session.removeAttribute("username");
application layer에서 session을 직접 다루는게 적합한 의존관계일까요??
아니라면 session은 어디에서 관리되어야 할까요??

2022-02-23 01:35 UTC, f-lab-bright commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +      Account account = accountRepository.findByEmail(loginAccountCommand.getEmail()).orElseThrow(
아직 완성된 코드가 아니긴 하겠지만, 패스워드 검증도 있어야 되겠네요 :)

2022-02-23 01:35 UTC, f-lab-bright commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +          () -> new NullPointerException("존재하지 않는 이메일")
NullPointException을 사용하는 것 보다는 의도가 더 잘 드러날 수 있는 예외를 직접 선언해서 사용하는게 좀 더 좋을 것 같네요

2022-02-23 01:35 UTC, f-lab-bright commented on src/main/java/com/interoffice/account/presentation/AccountApi.java
> +  public String login(@RequestParam String email, @RequestParam String password, HttpSession session) {
api의 응답으로 그냥 문자열을 반환하는건 그다지 좋은 방법은 아닐 것 같네요.
성공, 실패 시의 응답 형식을 어느정도 고정시키고, 항상 json으로 전달할 수 있는 방법은 없을까요??
간혹 특정 api를 rest가 아닌 형태로도 제공해야 한다면 어떻게 설계되는게 변경을 최소화하고 재사용성을 높일 수 있을까요?

2022-02-24 03:26 UTC, jws1837 approved these changes

2022-02-25 03:35 UTC, f-lab-bright approved these changes

2022-02-25 06:50 UTC, merged

2022-03-02 02:48 UTC, jws1837 commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +      session.setAttribute("username", account.getUsername());
Role과 고유id로 변경해봤습니다.

2022-03-02 02:56 UTC, jws1837 commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +    session.removeAttribute("username");
session정보는 db에 담아두는 경우도 많기 때문에,  infrastructure layer에서 관리하는 게 맞는 것 같아서, 로그인은 그렇게하고, logout은 초기화만 하면 된다고 생각해 controller단에서 처리해놓는 걸로 구현해놨는데, 일관성이 없는 거겠죠?

2022-03-02 02:57 UTC, jws1837 commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +      Account account = accountRepository.findByEmail(loginAccountCommand.getEmail()).orElseThrow(
네 간단하게 해놨습니다.

2022-03-02 02:58 UTC, jws1837 commented on src/main/java/com/interoffice/account/application/AccountFacade.java
> +          () -> new NullPointerException("존재하지 않는 이메일")
예외 객체 하나 만들어서 하려다가 코드가 늘어나는 게 좋은건지 잘 몰라서 illegalStateException으로 수정했습니다.

2022-03-02 03:00 UTC, jws1837 commented on src/main/java/com/interoffice/account/presentation/AccountApi.java
> +  public String login(@RequestParam String email, @RequestParam String password, HttpSession session) {
httpstatus로 반환하려다가, 바디정보까지 응답할 수 있는 responseEntity로 전달하는 걸로 수정했습니다.  rest가 아닌 형태에 대한 고려는 조금 더 스터디해보겠습니다.